[package]
name = "prost_504"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1.1.0"
prost = "0.7.0"
prost-types = "0.7.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.7.0"